server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # Auth Service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        # Product Service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
            - Path=/api/categories/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true

app:
  security:
    public-paths:
      - /api/auth