spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "product-service"
  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: product-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

kafka:
  topics:
    stock-reserved-topic: ${STOCK_RESERVED_TOPIC}
    stock-failed-topic: ${STOCK_FAILED_TOPIC}
