#!/bin/bash
set -e


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${AUTH_DB_NAME};
    CREATE USER ${AUTH_DB_USERNAME} WITH PASSWORD '${AUTH_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${AUTH_DB_NAME} TO ${AUTH_DB_USERNAME};
    
    \c ${AUTH_DB_NAME}
    GRANT ALL ON SCHEMA public TO ${AUTH_DB_USERNAME};
    
    \c ${POSTGRES_DB}
    
    CREATE DATABASE ${USER_DB_NAME};
    CREATE USER ${USER_DB_USERNAME} WITH PASSWORD '${USER_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${USER_DB_NAME} TO ${USER_DB_USERNAME};
    
    \c ${USER_DB_NAME}
    GRANT ALL ON SCHEMA public TO ${USER_DB_USERNAME};
EOSQL

echo "Databases and users created successfully!"